# Deployment do Postgre
apiversion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
	  app: postgre
  template:
    metadata:
	  labels:
	    app: postgre
	spec:
	  containers:
	    - name: postgre
		  image: postgre:14.3
		  ports:
		    - containerPort: 5432
		  env:
		  - name: POSTGRES_PASSWORD
		    value: "Kube@123#alberto"
		  - name: POSTGRES_USER
		    value: "kubenews"		
		  - name: POSTGRES_DB
		    value: "kubenews"			

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432 #porta utilizada pelo service
	targetPort: 5432 #porta utilizada pelo pod

			
---


apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 10
  selector:
    matchLabels:
	  app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
    	  image: albertoreboucas/kube-news:v1
		  env:
		  - name: DB_NAME
		  value: "kubenews"
		  - name: DB_USER
		  value: "kubenews"
		  - name: DB_PASSWORD
		  value: "Kube@123#alberto"
		  - name: DB_HOST
		  value: "postgre"  #nome do service


---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80 #porta utilizada pelo service
	targetPort: 8080 #porta utilizada pelo pod
	nodePort: 30000
  type: NodePort

			